version: '2'
services:
 master:
   image: vulhub/spark:2.3.1
   ports:
    - "18080:8080"
    - "17077:7077"
    - "16066:6066"
 slave:
   command: "slave spark://master:17077"
   image: vulhub/spark:2.3.1
   depends_on:
    - master
   ports:
    - "18081:8081"